### PR TITLE
#692 Template has pre filled input working, both before and after ope…

### LINKED ISSUE #692: Pre-filled template input does not work
When editing the template, the pre-filled values that appear in the Dialog should fill out the inputs in a template without editing the pre-filled values, but when Accepting the values and clicking Compile, an error appears - **_Flow can't have null inputs_**.
To make it work it is necessary to touch and edit the input fields and then click accept.

Steps to reproduce: Open Tagomi template editor for a service with template that has inputs and debugValues set, open the _**Fill Input**_ dialog and click _**Accept**_, click _**Compile**_ , in the PDF preview, it will remain NO PDF

It is supposed to accept the pre-filled values and compile the template without having to edit the input fields.

Image

### PR DESCRIPTION
**Pull request by NadirDulic**
https://github.com/user-attachments/assets/4e4ae91f-2e4b-40ce-9c1e-7eef1cc5cdd2

Made it so that when the user comes to the PDF editor, the debug values specified in a service flow are already available and user can click on the "Compile" button and it will show the PDF preview with the debug values. 
Also, the user can open the "Fill Input" button to see the values and click accept without needing to edit the fields, click "Compile", and it will compile the pdf with the pre filled values.

### CODE REVIEW

File: ts_setup/modules/tagomi-routes/tagomi-template/TemplateEditor.tsx [hunk 1]
```diff
@@ -20,14 +20,14 @@ export const TemplateEditor: React.FC<{ serviceId: string, templateId: string }>
...
   const composer = TagomiComposerApi.useComposer();
-  const [input, setInput] = React.useState<object>({});
   const [inputOpen, setInputOpen] = React.useState<boolean>(false);
   const [base64, setBase64] = React.useState<string>();
 
   const template = composer.site.templates[templateId];
   const service = composer.site.services[serviceId];
   const localeLabel = service.labels.find(l => l.locale === template.localeId)?.labelValue ?? '';
   const [src, setSrc] = React.useState(template.content);
+  const { input, setInput } = useGetFlowInput(service.orchestratorName);
```
Comment (olev-mutso) [inline ts_setup/modules/tagomi-routes/tagomi-template/TemplateEditor.tsx]: Naming improvement required.
useGetFlowInput = method returns get and set aka current state management
Keyword Get makes very little sense .... remove it.
