### PR TITLE
DT improvements

### LINKED ISSUE #650: DT small improvements
Image

1) Remove copy of this decision table function, decisions.toolbar.copyCommands, it not need here + it not working

2) Change CSV the file upload and download default type to "," instead of ";" . Upload supports both "," and ";" but download in only available as ";"

Image

3) Change text Task_events_dt - Column: ALL to Task_events_dt - Configure 

Image

Set **FIRST** as default Hit policy

### PR DESCRIPTION
**Pull request by admirkrilasevic**
### 1. New options menu

old toolbar replaced with new options menu, information about table name and hit policy moved to the right
image

### 2. Selecting CSV delimiter

users can now choose a delimiter when uploading or downloading CSV for DTs
  
image
image

### 3. Default hit policy - FIRST

when creating a new DT, the hit policy will be set to FIRST by default

### CODE REVIEW

File: mvn_setup/hdes-parent/hdes-client/src/main/java/io/resys/hdes/client/spi/decision/DecisionAstBuilderImpl.java [hunk 1]
```diff
@@ -159,8 +159,9 @@ protected CommandMapper.Builder execute(CommandMapper.Builder builder, AstComman
       case IMPORT_ORDERED_CSV: {
         
         CommandMapper.Builder result = builder.deleteColumns().deleteRows();
-        
-        CSVParser parser = CSVParser.parse(command.getValue(), CSVFormat.DEFAULT);
+        CSVFormat format = (command.getId() != null && !command.getId().isEmpty()) ?
```
Comment (olev-mutso) [inline mvn_setup/hdes-parent/hdes-client/src/main/java/io/resys/hdes/client/spi/decision/DecisionAstBuilderImpl.java]: Instead of double condition in if block use: org.apache.commons.lang3.StringUtils
